version: '3'

services:
  webos:
    image: devweb
    container_name: web1
    network_mode: "bridge"
    volumes:
      - web1:/var/www/html
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - dbos
    restart: always
    ports:
      - 1200:80

  dbos:
    image: mysql:5.7
    container_name: dbos
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: chouhan
      MYSQL_USER: Dharmvatsal
      MYSQL_PASSWORD: Singh
      MYSQL_DATABASE: mydbos

volumes:
  mysql_storage:
  web_storage_:
