version: '3'

services:
  webos:
    image: webkochar
    container_name: web2
    network_mode: "bridge"
    volumes:
      - web_storage:/var/www/html
    command: /bin/bash
    tty: true
    stdin_open: true
    depends_on:
      - dbos
    restart: always
    ports:
      - 1200:80

  dbos:
    image: mysql:5.7
    container_name: dbos
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: ashkochar
      MYSQL_USER: Ashishkochar
      MYSQL_PASSWORD: kochar
      MYSQL_DATABASE: mydbos

volumes:
  mysql_storage:
  web_storage_:
